FROM node:20 AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable
COPY --from=build /app/dist/ng-mathtrain/browser/ /usr/share/nginx/html

EXPOSE 80
